-- Version 1.4

-- Add authentication token
CREATE TABLE token (
  id bigint(20) PRIMARY KEY AUTO_INCREMENT,
  token varchar(255) NOT NULL COMMENT 'authentication token for the given user',
  clientId varchar(255) NOT NULL COMMENT 'client id generated by the client for the current token',
  clientType varchar(255) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  userId bigint(20) NOT NULL,
  merchantId bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE token ADD UNIQUE INDEX (userId, merchantId);
ALTER TABLE token ADD CONSTRAINT token_merchant_FK FOREIGN KEY (merchantId) REFERENCES merchant(id) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE token ADD CONSTRAINT token_user_FK FOREIGN KEY (userId) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE;

-- Add UUIDs
ALTER TABLE merchant ADD uuid VARCHAR(100) NOT NULL AFTER id;
UPDATE merchant SET uuid = (SELECT UUID()) WHERE merchant.id = 1;
UPDATE merchant SET uuid = (SELECT UUID()) WHERE merchant.id = 2;